name       : qt5-xmlpatterns
version    : 5.12.3
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtxmlpatterns-everywhere-src-5.12.3.tar.xz : e0b98e7c92cd791a9b354d090788347db78f14c47579384fe22d0b650c1d8a61
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LPGL-3.0
component  : desktop.qt
summary    : Qt5 XML Patterns
description: |
    The Qt XML Patterns module provides support for XPath, XQuery, XSLT, and XML Schema validation.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtxmlpatterns.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
