name       : qt5-xmlpatterns
version    : 5.15.2
release    : 22
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtxmlpatterns-everywhere-src-5.15.2.tar.xz : 76ea2162a7c349188d7e7e4f6c77b78e8a205494c90fee3cea3487a1ae2cf2fa
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LPGL-3.0-or-later
component  : desktop.qt
summary    : Qt5 XML Patterns
description: |
    The Qt XML Patterns module provides support for XPath, XQuery, XSLT, and XML Schema validation.
builddeps  :
    - pkgconfig(Qt5Quick)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtxmlpatterns.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
