name       : qt5-xmlpatterns
version    : 5.15.5
release    : 27
source     :
    - git|https://invent.kde.org/qt/qt/qtxmlpatterns.git : a8edba5ad50d669aead4ddb769f171cba892d676
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LPGL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 XML Patterns
description: |
    The Qt XML Patterns module provides support for XPath, XQuery, XSLT, and XML Schema validation.
builddeps  :
    - pkgconfig(Qt5Quick)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtxmlpatterns.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
