name       : qt5-xmlpatterns
version    : 5.13.2
release    : 18
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtxmlpatterns-everywhere-src-5.13.2.tar.xz : 1e87d8c004ec0beea3b29d13f0964c563aa9fae51c392c998750ca4e386374e2
homepage   : https://www.qt.io
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LPGL-3.0
component  : desktop.qt
summary    : Qt5 XML Patterns
description: |
    The Qt XML Patterns module provides support for XPath, XQuery, XSLT, and XML Schema validation.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtxmlpatterns.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
