name       : qt5-xmlpatterns
version    : 5.14.2
release    : 20
source     :
    - https://download.qt.io/official_releases/qt/5.14/5.14.2/submodules/qtxmlpatterns-everywhere-src-5.14.2.tar.xz : 219a876665345e3801baff71f31f30f5495c1cb9ab23fbbd27602632c80fcfb7
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LPGL-3.0-or-later
component  : desktop.qt
summary    : Qt5 XML Patterns
description: |
    The Qt XML Patterns module provides support for XPath, XQuery, XSLT, and XML Schema validation.
builddeps  :
    - pkgconfig(Qt5Quick)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtxmlpatterns.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
