name       : qt5-xmlpatterns
version    : 5.12.1
release    : 13
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtxmlpatterns-everywhere-src-5.12.1.tar.xz : 76988ca9a7a184b9013b8a5864dad150e4603890c7eb7aecad4baad071802ecb
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LPGL-3.0
component  : desktop.qt
summary    : Qt5 XML Patterns
description: |
    The Qt XML Patterns module provides support for XPath, XQuery, XSLT, and XML Schema validation.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtxmlpatterns.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
