name       : qt5-xmlpatterns
version    : 5.15.4
release    : 26
source     :
    - git|https://invent.kde.org/qt/qt/qtxmlpatterns.git : dfcae10dec8c1c2c544ad0cd303cea113b0af51d
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LPGL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 XML Patterns
description: |
    The Qt XML Patterns module provides support for XPath, XQuery, XSLT, and XML Schema validation.
builddeps  :
    - pkgconfig(Qt5Quick)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtxmlpatterns.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
