name       : qt5-xmlpatterns
version    : 5.11.1
release    : 10
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qtxmlpatterns-everywhere-src-5.11.1.tar.xz : 6117e120c87b32dd07877dd0a6bf862b6285cb0d8b547190882980682f53af58
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LPGL-3.0
component  : desktop.qt
summary    : Qt5 XML Patterns
description: |
    The Qt XML Patterns module provides support for XPath, XQuery, XSLT, and XML Schema validation.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtxmlpatterns.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
